# Generated by Django 4.2.7 on 2023-11-13 16:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finder', '0002_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='FileModel',
        ),
        migrations.RenameModel(
            old_name='Folder',
            new_name='FolderModel',
        ),
    ]
