# Generated by Django 4.2.7 on 2023-11-13 17:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finder', '0003_rename_file_filemodel_rename_folder_foldermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageModel',
        ),
    ]
