# Generated by Django 4.1.13 on 2023-11-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_rename_image_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldermodel',
            name='site',
            field=models.CharField(default='admin', editable=False, max_length=200, verbose_name='Site'),
        ),
    ]
