# Generated by Django 2.1.9 on 2019-06-25 19:12

import mimetypes

from django.db import migrations, models

import filer.models.filemodels


def guess_mimetypes_file(apps, schema_editor):
    FileModel = apps.get_model('filer', 'File')
    for fileobj in FileModel.objects.all():
        fileobj.mime_type, _ = mimetypes.guess_type(fileobj.file.path)
        fileobj.save(update_fields=['mime_type'])

def guess_mimetypes_image(apps, schema_editor):
    FileModel = apps.get_model('filer', 'Image')
    for fileobj in FileModel.objects.all():
        fileobj.mime_type, _ = mimetypes.guess_type(fileobj.file.path)
        fileobj.save(update_fields=['mime_type'])

class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='mime_type',
            field=models.CharField(default='application/octet-stream', help_text='MIME type of uploaded content', max_length=255, validators=[filer.models.filemodels.mimetype_validator]),
        ),
        migrations.RunPython(guess_mimetypes_file, reverse_code=migrations.RunPython.noop),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='mime_type',
            field=models.CharField(default='application/octet-stream', help_text='MIME type of uploaded content', max_length=255, validators=[filer.models.filemodels.mimetype_validator]),
        ),
        migrations.RunPython(guess_mimetypes_image, reverse_code=migrations.RunPython.noop),
    ]
